USE rfid_buc;
INSERT INTO qr_codes (chariot_id, qr_content) VALUES ('CH_1_FEEDER2', 'CHARIOT:CH_1_FEEDER2') ON DUPLICATE KEY UPDATE qr_content='CHARIOT:CH_1_FEEDER2';
INSERT INTO qr_codes (chariot_id, qr_content) VALUES ('CH_2_FEEDER2', 'CHARIOT:CH_2_FEEDER2') ON DUPLICATE KEY UPDATE qr_content='CHARIOT:CH_2_FEEDER2';
INSERT INTO qr_codes (chariot_id, qr_content) VALUES ('CH_3_FEEDER3', 'CHARIOT:CH_3_FEEDER3') ON DUPLICATE KEY UPDATE qr_content='CHARIOT:CH_3_FEEDER3';
INSERT INTO qr_codes (chariot_id, qr_content) VALUES ('CH_4_POSTE1', 'CHARIOT:CH_4_POSTE1') ON DUPLICATE KEY UPDATE qr_content='CHARIOT:CH_4_POSTE1';